name: DEV - Static Bucket

on:
  pull_request:
    branches: [master]

jobs:
  deploy-dev:
    name: DEV - Deploy static assets to storage bucket
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - id: checkout
        uses: actions/checkout@v4

      - id: install
        name: Install dependencies
        run: yarn install

      - id: test
        name: Test
        run: yarn ci

      - id: build
        name: Build
        run: yarn build
        env:
          SAMPLER_BASE_URL: sampling-dev.tvping.com

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          project_id: tv-insight-cd
          credentials_json: ${{ secrets.GCP_TRACKING_SAMPLING_SA_KEY }}

      - id: upload
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: dist
          destination: sampling-content-dev-tvping-com
          parent: false
          predefinedAcl: publicRead
          glob: "!(**/*.html)" # WARNING this glob is not working due to https://github.com/mrmlnc/fast-glob/issues/343 Assure that html files are uploaded AFTER uploading of other files so that content-type is changed!!!
          headers: |-
            cache-control: public, max-age=3600
          process_gcloudignore: false

      - id: upload_html
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: dist
          destination: sampling-content-dev-tvping-com
          parent: false
          predefinedAcl: publicRead
          glob: "**/*.html"
          headers: |-
            content-type: application/vnd.hbbtv.xhtml+xml
            cache-control: public, max-age=3600
          process_gcloudignore: false
