name: DEV - Static Bucket

on:
  push:
    branches:
      - "develop"
      - "feature/*"
      - "release/*"
      - "hotfix/*"

jobs:
  deploy-dev:
    name: DEV - Deploy static assets to storage bucket
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - id: checkout
        uses: actions/checkout@v4

      - id: install
        name: Install dependencies
        run: yarn install

      - id: test
        name: Test
        run: yarn ci

      - id: build-config
        name: Write build config
        uses: devops-actions/json-to-file@v1.0.4
        with:
          filename: "build.json"
          json: |
            {
              "": {
                "SAMPLER_HOST": "sampling-dev.tvping.com",
                "IN_SAMPLE_PERCENTILE": 10,
                "TECHNICAL_COOKIE_MIN_AGE": 172800000,
                "TECHNICAL_COOKIE_NAME": "x-sampler-t",
                "PERCENTILE_COOKIE_NAME": "x-sampler-p"
              },
              "de-ip": {
                "SAMPLER_HOST": "sampling.tvping.com",
                "IN_SAMPLE_PERCENTILE": 10,
                "TECHNICAL_COOKIE_MIN_AGE": 172800000,
                "TECHNICAL_COOKIE_NAME": "x-sampler-t",
                "PERCENTILE_COOKIE_NAME": "x-sampler-p"
              },
              "de-p7s1": {
                "SAMPLER_HOST": "sampling.tvping.com",
                "IN_SAMPLE_PERCENTILE": 100,
                "TECHNICAL_COOKIE_MIN_AGE": 172800000,
                "TECHNICAL_COOKIE_NAME": "x-sampler-t",
                "PERCENTILE_COOKIE_NAME": "x-sampler-p"
              }
            }

      - id: build
        name: Build
        run: yarn build

      - id: auth
        if: github.ref == 'refs/heads/develop'
        uses: google-github-actions/auth@v2
        with:
          project_id: tv-insight-cd
          credentials_json: ${{ secrets.GCP_TRACKING_SAMPLING_SA_KEY }}

      - id: upload
        if: github.ref == 'refs/heads/develop'
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: dist
          destination: sampling-content-dev-tvping-com
          parent: false
          predefinedAcl: publicRead
          process_gcloudignore: false
