name: DEV - Static Bucket

on:
  push:
    branches:
      - "develop"
      - "feature/*"
      - "release/*"
      - "hotfix/*"

jobs:
  deploy-dev:
    name: DEV - Deploy static assets to storage bucket
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - id: checkout
        uses: actions/checkout@v4

      - id: install
        name: Install dependencies
        run: yarn install

      - id: test
        name: Test
        run: yarn ci

      - id: build
        name: Build
        run: yarn build --config ./config/dev.json

      - id: zip
        if: github.ref == 'refs/heads/develop'
        name: Zip templates
        run: zip -r -j templates.zip ./dist/*

      - id: snapshot
        if: github.ref == 'refs/heads/develop'
        name: Create snapshot tag
        run: |
          echo 'version=snapshot_${{ github.run_number }}' >> $GITHUB_OUTPUT

      - id: release
        if: github.ref == 'refs/heads/develop'
        name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.snapshot.outputs.version }}
          tag_name: ${{ steps.snapshot.outputs.version }}
          files: |
            templates.zip
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
