name: PROD - Static Bucket

on:
  push:
    branches:
      - "!develop"
      - "master"
    tags:
      - "v*.*.*"

jobs:
  deploy:
    name: PROD - Deploy static assets to storage bucket
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - id: checkout
        uses: actions/checkout@v4

      - id: install
        name: Install dependencies
        run: yarn install

      - id: test
        name: Test
        run: yarn ci

      - id: build
        name: Build
        run: yarn build --config ./config/prod.json

      - id: zip
        name: Zip templates
        run: zip -r -j templates.zip ./dist/*

      - id: release
        name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{  github.ref_name }}
          files: |
            templates.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
