name: PROD - Static Bucket

on:
  push:
    branches:
      - "!develop"
    tags:
      - "v*.*.*"

jobs:
  deploy:
    name: PROD - Deploy static assets to storage bucket
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - id: checkout
        uses: actions/checkout@v4

      - id: install
        name: Install dependencies
        run: yarn install

      - id: test
        name: Test
        run: yarn ci

      - id: build-config
        name: Write build config
        uses: devops-actions/json-to-file@v1.0.4
        with:
          filename: "build.json"
          json: |
            {
              "": {
                "SAMPLER_HOST": "sampling.tvping.com",
                "MAX_PERCENTILE": 10,
                "TECHNICAL_COOKIE_MIN_AGE": 172800000,
                "TECHNICAL_COOKIE_NAME": "x-sampler-t",
                "PERCENTILE_COOKIE_NAME": "x-sampler-p"
              },
              "agf": {
                "SAMPLER_HOST": "sampling.tvping.com",
                "MAX_PERCENTILE": 10,
                "TECHNICAL_COOKIE_MIN_AGE": 172800000,
                "TECHNICAL_COOKIE_NAME": "x-sampler-agf-t",
                "PERCENTILE_COOKIE_NAME": "x-sampler-agf-p"
              }
            }

      - id: build
        name: Build
        run: yarn build

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          project_id: tv-insight-cd
          credentials_json: ${{ secrets.GCP_TRACKING_SAMPLING_SA_KEY }}

      - id: upload
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: dist
          destination: sampling-content-tvping-com
          parent: false
          predefinedAcl: publicRead
          glob: "**/*.js"
          headers: |-
            cache-control: public, max-age=3600
          process_gcloudignore: false

      - id: upload_html
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: dist
          destination: sampling-content-tvping-com
          parent: false
          predefinedAcl: publicRead
          glob: "**/*.html"
          headers: |-
            content-type: application/vnd.hbbtv.xhtml+xml
            cache-control: public, max-age=3600
          process_gcloudignore: false
