name: AI Code Review

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions: write-all
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: AI Code Reviewer
        uses: lfsevergnini/ai-codereviewer@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AI_PROVIDER: "openai"
          AI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          AI_MODEL: "gpt-4o-mini"
          AI_TEMPERATURE: 0.3
          APPROVE_REVIEWS: false
          MAX_COMMENTS: 0
          PROJECT_CONTEXT: "This is a script to be used on HbbTV devices to assign a device to a random percentile in order to be part of a big sampling group"
          CONTEXT_FILES: "package.json,README.md"
          EXCLUDE_PATTERNS: "**/*.lock,**/*.json,**/*.md,**/*.yaml"
